export interface QuestionOption {
  value: string;
  label: string;
}

export interface QuestionDef {
  id: string;
  question: string;
  type: "single" | "multi";
  options: QuestionOption[];
  optional?: boolean;
}

export const ageQuestion = {
  id: "age",
  question: "Qual é a idade da pessoa para quem você está buscando atendimento?",
  helper: "Use um número inteiro, entre 0 e 120 anos.",
};

export const branchAQuestions: QuestionDef[] = [
  {
    id: "a1_respondent",
    question: "Quem está respondendo?",
    type: "single",
    options: [
      { value: "mae", label: "Mãe" },
      { value: "pai", label: "Pai" },
      { value: "responsavel_legal", label: "Responsável legal" },
      { value: "familiar_autorizado", label: "Familiar autorizado" },
      { value: "outra_pessoa_autorizada", label: "Outra pessoa autorizada" },
    ],
  },
  {
    id: "a2_motivations",
    question: "O que motivou a busca pelo Instituto?",
    type: "multi",
    options: [
      { value: "dificuldades_escola", label: "Dificuldades na escola" },
      { value: "dificuldades_leitura_escrita", label: "Dificuldades de leitura ou escrita" },
      { value: "dificuldades_matematica", label: "Dificuldades em matemática" },
      { value: "desatencao", label: "Desatenção ou dificuldade de concentração" },
      { value: "esquecimentos", label: "Esquecimentos frequentes" },
      { value: "dificuldade_organizacao", label: "Dificuldade de organização" },
      { value: "dificuldade_iniciar_concluir", label: "Dificuldade para iniciar ou concluir atividades" },
      { value: "desenvolvimento_diferente", label: "Desenvolvimento diferente do esperado" },
      { value: "mudancas_comportamento", label: "Mudanças de comportamento" },
      { value: "ansiedade_autorregulacao", label: "Ansiedade ou dificuldade de autorregulação" },
      { value: "queda_desempenho_escolar", label: "Queda no desempenho escolar" },
      { value: "orientacao_escola", label: "Orientação da escola" },
      { value: "orientacao_profissional", label: "Orientação de outro profissional" },
      { value: "compreender_necessidades", label: "Desejo compreender melhor as necessidades da criança ou do adolescente" },
    ],
  },
  {
    id: "a3_duration",
    question: "Há quanto tempo essas dificuldades são percebidas?",
    type: "single",
    options: [
      { value: "menos_3_meses", label: "Há menos de 3 meses" },
      { value: "3_a_6_meses", label: "Entre 3 e 6 meses" },
      { value: "mais_6_meses", label: "Há mais de 6 meses" },
      { value: "mais_1_ano", label: "Há mais de 1 ano" },
      { value: "sempre", label: "Sempre estiveram presentes" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "a4_schoolPerformance",
    question: "Como está o desempenho escolar atualmente?",
    type: "single",
    options: [
      { value: "adequado", label: "Adequado para a idade e o ano escolar" },
      { value: "dificuldade_algumas_materias", label: "Dificuldade em algumas matérias" },
      { value: "dificuldade_varias_materias", label: "Dificuldades em várias matérias" },
      { value: "queda_recente", label: "Houve uma queda recente no desempenho" },
      { value: "nao_frequenta_escola", label: "Ainda não frequenta a escola" },
      { value: "nao_sei_avaliar", label: "Não sei avaliar" },
    ],
  },
  {
    id: "a5_learningDifficulties",
    question: "Quais dificuldades relacionadas à aprendizagem são percebidas?",
    type: "multi",
    options: [
      { value: "leitura", label: "Leitura" },
      { value: "escrita", label: "Escrita" },
      { value: "ortografia", label: "Ortografia" },
      { value: "compreensao_textos", label: "Compreensão de textos" },
      { value: "matematica", label: "Matemática" },
      { value: "acompanhamento_conteudo", label: "Acompanhamento do conteúdo escolar" },
      { value: "realizacao_atividades", label: "Realização das atividades" },
      { value: "demora_concluir", label: "Demora excessiva para concluir tarefas" },
      { value: "necessidade_ajuda", label: "Necessidade constante de ajuda" },
      { value: "sem_dificuldades", label: "Não percebo dificuldades significativas" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "a6_attentionOrganization",
    question: "Em relação à atenção e à organização, o que é observado?",
    type: "multi",
    options: [
      { value: "distrai_facilidade", label: "Distrai-se com facilidade" },
      { value: "dificuldade_concentracao", label: "Tem dificuldade para manter a concentração" },
      { value: "dificuldade_concluir", label: "Tem dificuldade para concluir tarefas" },
      { value: "muitos_lembretes", label: "Precisa de muitos lembretes" },
      { value: "erros_falta_atencao", label: "Comete erros por falta de atenção" },
      { value: "esquece_materiais", label: "Esquece materiais, atividades ou compromissos" },
      { value: "dificuldade_iniciar", label: "Tem dificuldade para iniciar tarefas" },
      { value: "dificuldade_seguir_instrucoes", label: "Tem dificuldade para seguir etapas ou instruções" },
      { value: "foco_interesse", label: "Concentra-se principalmente em assuntos de interesse" },
      { value: "sem_dificuldades", label: "Não percebo dificuldades significativas" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "a7_frustrationReaction",
    question: "Como reage diante de erros, mudanças ou frustrações?",
    type: "multi",
    options: [
      { value: "lida_adequadamente", label: "Consegue lidar de maneira adequada" },
      { value: "frustra_recupera", label: "Fica frustrado, mas se recupera" },
      { value: "desiste_facilmente", label: "Desiste facilmente" },
      { value: "evita_medo_errar", label: "Evita atividades por medo de errar" },
      { value: "ansiedade", label: "Demonstra ansiedade" },
      { value: "reacoes_intensas", label: "Apresenta reações emocionais intensas" },
      { value: "dificuldade_mudancas", label: "Tem dificuldade para aceitar mudanças" },
      { value: "tempo_reorganizar", label: "Precisa de muito tempo para se reorganizar" },
      { value: "nao_sei_avaliar", label: "Não sei avaliar" },
    ],
  },
  {
    id: "a8_environments",
    question: "Em quais ambientes essas dificuldades aparecem?",
    type: "multi",
    options: [
      { value: "casa", label: "Em casa" },
      { value: "escola", label: "Na escola" },
      { value: "extracurriculares", label: "Em atividades extracurriculares" },
      { value: "situacoes_sociais", label: "Em situações sociais" },
      { value: "quase_todos", label: "Em quase todos os ambientes" },
      { value: "situacoes_especificas", label: "Apenas em situações específicas" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "a9_schoolConcern",
    question: "A escola já apresentou alguma preocupação?",
    type: "single",
    options: [
      { value: "sim_aprendizagem", label: "Sim, relacionada à aprendizagem" },
      { value: "sim_atencao", label: "Sim, relacionada à atenção" },
      { value: "sim_comportamento", label: "Sim, relacionada ao comportamento" },
      { value: "sim_desenvolvimento", label: "Sim, relacionada ao desenvolvimento" },
      { value: "sim_mais_de_uma", label: "Sim, relacionada a mais de uma área" },
      { value: "nao", label: "Não" },
      { value: "nao_frequenta", label: "A criança ainda não frequenta a escola" },
    ],
  },
  {
    id: "a10_priorDiagnosis",
    question: "Já existe diagnóstico, avaliação ou acompanhamento profissional?",
    type: "single",
    optional: true,
    options: [
      { value: "diagnostico_acompanha", label: "Possui diagnóstico e realiza acompanhamento" },
      { value: "diagnostico_sem_acompanhar", label: "Possui diagnóstico, mas não realiza acompanhamento atualmente" },
      { value: "investigacao", label: "Está em processo de investigação" },
      { value: "avaliacao_anterior", label: "Já realizou avaliação anteriormente" },
      { value: "acompanhamento_anterior", label: "Já realizou acompanhamento anteriormente" },
      { value: "nunca_realizou", label: "Nunca realizou avaliação ou acompanhamento" },
      { value: "prefiro_informar_contato", label: "Prefiro informar durante o contato" },
    ],
  },
  {
    id: "a11_familyGoal",
    question: "O que a família procura neste momento?",
    type: "single",
    options: [
      { value: "compreender_dificuldades", label: "Compreender melhor as dificuldades" },
      { value: "avaliacao_especializada", label: "Realizar uma avaliação especializada" },
      { value: "acompanhamento_individualizado", label: "Iniciar um acompanhamento individualizado" },
      { value: "desenvolver_habilidades", label: "Desenvolver habilidades de aprendizagem" },
      { value: "melhorar_atencao_memoria", label: "Melhorar atenção, memória ou organização" },
      { value: "conhecer_neurofeedback", label: "Conhecer o Neurofeedback" },
      { value: "conhecer_neuromodulacao", label: "Conhecer o Programa de Neuromodulação" },
      { value: "continuidade_indicacao", label: "Dar continuidade à indicação de outro profissional" },
      { value: "nao_sabemos", label: "Ainda não sabemos qual é o melhor caminho" },
    ],
  },
];

export const branchBQuestions: QuestionDef[] = [
  {
    id: "b1_respondent",
    question: "Quem está respondendo?",
    type: "single",
    options: [
      { value: "propria_pessoa", label: "A própria pessoa que busca atendimento" },
      { value: "familiar", label: "Um familiar" },
      { value: "responsavel_representante", label: "Um responsável ou representante" },
      { value: "cuidador", label: "Um cuidador" },
      { value: "outra_pessoa_autorizada", label: "Outra pessoa autorizada" },
    ],
  },
  {
    id: "b2_motivations",
    question: "O que motivou a busca pelo Instituto?",
    type: "multi",
    options: [
      { value: "dificuldade_atencao", label: "Dificuldade de atenção" },
      { value: "dificuldade_concentracao", label: "Dificuldade de concentração" },
      { value: "esquecimentos", label: "Esquecimentos frequentes" },
      { value: "dificuldade_organizacao", label: "Dificuldade de organização" },
      { value: "dificuldade_iniciar_concluir", label: "Dificuldade para iniciar ou concluir tarefas" },
      { value: "cansaco_mental", label: "Cansaço mental" },
      { value: "queda_desempenho_cognitivo", label: "Queda percebida no desempenho cognitivo" },
      { value: "dificuldade_estudos", label: "Dificuldade nos estudos" },
      { value: "dificuldade_trabalho", label: "Dificuldade no trabalho" },
      { value: "ansiedade_autorregulacao", label: "Ansiedade ou dificuldade de autorregulação" },
      { value: "desejo_melhorar_desempenho", label: "Desejo de melhorar o desempenho cognitivo" },
      { value: "indicacao_profissional", label: "Indicação de outro profissional" },
      { value: "interesse_neurofeedback", label: "Interesse em Neurofeedback" },
      { value: "interesse_neuromodulacao", label: "Interesse em Neuromodulação" },
      { value: "conhecer_servicos", label: "Desejo de conhecer melhor os serviços" },
    ],
  },
  {
    id: "b3_duration",
    question: "Há quanto tempo essas dificuldades ou necessidades são percebidas?",
    type: "single",
    options: [
      { value: "menos_3_meses", label: "Há menos de 3 meses" },
      { value: "3_a_6_meses", label: "Entre 3 e 6 meses" },
      { value: "mais_6_meses", label: "Há mais de 6 meses" },
      { value: "mais_1_ano", label: "Há mais de 1 ano" },
      { value: "objetivo_desenvolvimento", label: "Não se trata de uma dificuldade específica, mas de um objetivo de desenvolvimento" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "b4_aspects",
    question: "Quais aspectos são percebidos atualmente?",
    type: "multi",
    options: [
      { value: "distracao_frequente", label: "Distração frequente" },
      { value: "dificuldade_concentracao", label: "Dificuldade para manter a concentração" },
      { value: "esquecimento_informacoes", label: "Esquecimento de informações ou compromissos" },
      { value: "dificuldade_organizar_rotina", label: "Dificuldade para organizar a rotina" },
      { value: "procrastinacao", label: "Procrastinação ou dificuldade para iniciar tarefas" },
      { value: "dificuldade_concluir", label: "Dificuldade para concluir atividades" },
      { value: "lentidao_mental", label: "Sensação de lentidão mental" },
      { value: "dificuldade_varias_demandas", label: "Dificuldade para lidar com várias demandas" },
      { value: "oscilacoes_desempenho", label: "Oscilações no desempenho" },
      { value: "dificuldade_autorregulacao", label: "Dificuldade de autorregulação" },
      { value: "sem_dificuldade", label: "Não percebo uma dificuldade específica" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "b5_interferenceAreas",
    question: "Em quais áreas isso interfere?",
    type: "multi",
    options: [
      { value: "trabalho", label: "Trabalho" },
      { value: "estudos", label: "Estudos" },
      { value: "rotina", label: "Organização da rotina" },
      { value: "relacionamentos", label: "Relacionamentos" },
      { value: "atividades_diarias", label: "Atividades diárias" },
      { value: "bem_estar_emocional", label: "Bem-estar emocional" },
      { value: "varias_areas", label: "Em várias áreas" },
      { value: "sem_interferencia", label: "Não existe interferência importante, mas há um objetivo de desenvolvimento" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "b6_priorDiagnosis",
    question: "Já existe diagnóstico ou acompanhamento profissional?",
    type: "single",
    optional: true,
    options: [
      { value: "diagnostico_acompanha", label: "Possui diagnóstico e realiza acompanhamento" },
      { value: "diagnostico_sem_acompanhar", label: "Possui diagnóstico, mas não realiza acompanhamento atualmente" },
      { value: "investigacao", label: "Está em processo de investigação" },
      { value: "acompanhamento_anterior", label: "Já realizou acompanhamento anteriormente" },
      { value: "indicacao_profissional", label: "Recebeu indicação de outro profissional" },
      { value: "nunca_realizou", label: "Nunca realizou avaliação ou acompanhamento" },
      { value: "prefiro_informar_contato", label: "Prefiro informar durante o contato" },
    ],
  },
  {
    id: "b7_goal",
    question: "O que você procura neste momento?",
    type: "single",
    options: [
      { value: "melhorar_atencao_concentracao", label: "Melhorar atenção e concentração" },
      { value: "desenvolver_memoria_organizacao", label: "Desenvolver memória e organização" },
      { value: "melhorar_estudos", label: "Melhorar o desempenho nos estudos" },
      { value: "melhorar_profissional", label: "Melhorar o desempenho profissional" },
      { value: "desenvolver_autorregulacao", label: "Desenvolver autorregulação" },
      { value: "conhecer_neurofeedback", label: "Conhecer o Neurofeedback" },
      { value: "conhecer_neuromodulacao", label: "Conhecer o Programa de Neuromodulação" },
      { value: "continuidade_recomendacao", label: "Dar continuidade a uma recomendação profissional" },
      { value: "compreender_servico", label: "Compreender qual serviço é mais adequado" },
      { value: "nao_sei", label: "Ainda não sei qual é o melhor caminho" },
    ],
  },
];

export const branchCQuestions: QuestionDef[] = [
  {
    id: "c1_respondent",
    question: "Quem está respondendo?",
    type: "single",
    options: [
      { value: "propria_pessoa", label: "A própria pessoa que busca atendimento" },
      { value: "filho_filha", label: "Filho ou filha" },
      { value: "outro_familiar", label: "Outro familiar" },
      { value: "cuidador", label: "Cuidador" },
      { value: "responsavel_representante", label: "Responsável ou representante" },
      { value: "outra_pessoa_autorizada", label: "Outra pessoa autorizada" },
    ],
  },
  {
    id: "c2_motivations",
    question: "O que motivou a busca pelo Instituto?",
    type: "multi",
    options: [
      { value: "esquecimentos", label: "Esquecimentos frequentes" },
      { value: "dificuldade_atencao", label: "Dificuldade de atenção" },
      { value: "dificuldade_concentracao", label: "Dificuldade de concentração" },
      { value: "dificuldade_organizacao", label: "Dificuldade de organização" },
      { value: "lentidao", label: "Percepção de maior lentidão para realizar atividades" },
      { value: "mudanca_funcionamento", label: "Mudança percebida no funcionamento cognitivo" },
      { value: "dificuldade_acompanhar_conversas", label: "Dificuldade para acompanhar conversas ou informações" },
      { value: "estimular_habilidades", label: "Desejo de estimular habilidades cognitivas" },
      { value: "dificuldade_autorregulacao", label: "Dificuldade de autorregulação" },
      { value: "indicacao_medica", label: "Indicação médica ou de outro profissional" },
      { value: "interesse_neurofeedback", label: "Interesse em Neurofeedback" },
      { value: "interesse_neuromodulacao", label: "Interesse em Neuromodulação" },
      { value: "conhecer_servicos", label: "Desejo de conhecer melhor os serviços" },
    ],
  },
  {
    id: "c3_duration",
    question: "Há quanto tempo essas mudanças ou necessidades são percebidas?",
    type: "single",
    options: [
      { value: "menos_3_meses", label: "Há menos de 3 meses" },
      { value: "3_a_6_meses", label: "Entre 3 e 6 meses" },
      { value: "mais_6_meses", label: "Há mais de 6 meses" },
      { value: "mais_1_ano", label: "Há mais de 1 ano" },
      { value: "sem_mudanca_especifica", label: "Não há uma mudança específica, mas existe interesse em estimulação cognitiva" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "c4_observed",
    question: "O que tem sido observado?",
    type: "multi",
    options: [
      { value: "esquecimento_compromissos", label: "Esquecimento de compromissos ou informações" },
      { value: "dificuldade_atencao", label: "Dificuldade para manter a atenção" },
      { value: "dificuldade_organizar", label: "Dificuldade para organizar atividades" },
      { value: "mais_tempo_tarefas", label: "Necessidade de mais tempo para realizar tarefas" },
      { value: "dificuldade_varias_informacoes", label: "Dificuldade para acompanhar várias informações" },
      { value: "oscilacoes_desempenho", label: "Oscilações no desempenho cognitivo" },
      { value: "dificuldade_autorregulacao", label: "Dificuldade de autorregulação" },
      { value: "sem_dificuldades", label: "Não percebo dificuldades significativas" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "c5_routineInterference",
    question: "Essas questões interferem na rotina?",
    type: "single",
    options: [
      { value: "nao_interferem", label: "Não interferem de forma significativa" },
      { value: "interferem_algumas", label: "Interferem em algumas atividades" },
      { value: "interferem_frequentemente", label: "Interferem frequentemente" },
      { value: "familia_percebe_mais", label: "A família percebe mais dificuldades do que a própria pessoa" },
      { value: "objetivo_manutencao", label: "O objetivo principal é manutenção ou estimulação cognitiva" },
      { value: "nao_certeza", label: "Não tenho certeza" },
    ],
  },
  {
    id: "c6_suddenChange",
    question: "As mudanças foram repentinas ou ocorreram em pouco tempo?",
    type: "single",
    options: [
      { value: "sim", label: "Sim" },
      { value: "nao", label: "Não" },
      { value: "nao_certeza", label: "Não tenho certeza" },
      { value: "sem_mudanca", label: "Não houve mudança, apenas interesse em estimulação cognitiva" },
    ],
  },
  {
    id: "c7_medicalFollowUp",
    question: "Existe acompanhamento médico ou de outro profissional?",
    type: "single",
    optional: true,
    options: [
      { value: "sim_atualmente", label: "Sim, realiza acompanhamento atualmente" },
      { value: "sim_indicacao", label: "Sim, e houve indicação para buscar o Instituto" },
      { value: "acompanhamento_anterior", label: "Já realizou acompanhamento anteriormente" },
      { value: "investigacao", label: "Está em processo de investigação" },
      { value: "nao_realiza", label: "Não realiza acompanhamento" },
      { value: "prefiro_informar_contato", label: "Prefiro informar durante o contato" },
    ],
  },
  {
    id: "c8_goal",
    question: "Qual é o principal objetivo neste momento?",
    type: "single",
    options: [
      { value: "atencao_concentracao", label: "Trabalhar atenção e concentração" },
      { value: "memoria_organizacao", label: "Trabalhar memória e organização" },
      { value: "estimular_habilidades", label: "Estimular habilidades cognitivas" },
      { value: "favorecer_atividades", label: "Favorecer o desempenho nas atividades diárias" },
      { value: "conhecer_neurofeedback", label: "Conhecer o Neurofeedback" },
      { value: "conhecer_neuromodulacao", label: "Conhecer o Programa de Neuromodulação" },
      { value: "continuidade_indicacao", label: "Dar continuidade à indicação de outro profissional" },
      { value: "compreender_servico", label: "Compreender qual serviço é mais adequado" },
      { value: "nao_sabemos", label: "Ainda não sabemos qual é o melhor caminho" },
    ],
  },
];

export const bestContactTimeOptions: QuestionOption[] = [
  { value: "manha", label: "Manhã" },
  { value: "tarde", label: "Tarde" },
  { value: "noite", label: "Noite" },
  { value: "qualquer", label: "Qualquer horário" },
];
